### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by pascallouisperez** [helloeave/worksheets#60]
We'd like to add support for enums
```
type my_enum enum {
  1:option_1
  2:option_3
}
```
In the db, we'd store only the index numbers for forward/backward compatibility.

When setting a value, not sure if `NewEnum` would make sense since you'd also need to reference the type. But maybe we could have an "untyped" enum value, i.e. just a string whose intent is to be used as an enum, which when it is being set checks against the options. On the other hand, if you receive an enum by doing a `Get` the type of enum would be known. Something to explore.

**Comment by cbelsole** [comment]
Is this structure incompatible with worksheets? For instance if worksheets looked like:
```
type simple worksheet {
  42:full_name text
  42:happy bool
}
```

You would not have to make the decision at the top node whether you were defining a worksheet or a type.

**Comment by pascallouisperez** [comment]
@cbelsole Let's go with your suggestion, and change the syntax to
```
type name worksheet { ...
type name enum { ...
```
From a language standpoint, this clearly puts worksheets and enum declarations on the same level: defining new types.

It also makes it easier to see future extensions such as constrained types such as
```
type ssn number[0] constrained_by {
  return 100_00_0000 <= ssn && ssn <= 999_99_999
}
```
which we had imagined could be expressed as #22 but would actually be much nicer that way.

**Comment by pascallouisperez** [comment]
Done.
